import { readFile, writeFile } from "node:fs/promises";

const wasmUrl = new URL("../src/extractor/generated/vaportrail_extractor_wasm_bg.wasm", import.meta.url);
const outputUrl = new URL("../src/extractor/generated/wasm-bytes.ts", import.meta.url);

const bytes = await readFile(wasmUrl);
const base64 = bytes.toString("base64");

await writeFile(
  outputUrl,
  [
    "// Generated by scripts/embed-wasm.mjs.",
    `export const wasmBase64 = ${JSON.stringify(base64)};`,
    `export const wasmByteLength = ${bytes.byteLength};`,
    "",
  ].join("\n"),
);

console.log(`Embedded ${bytes.byteLength} WASM bytes.`);
